In [498]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [499]:
df = pd.read_csv('PEA04.20231018T191000.csv')
df.head()

,STATISTIC Label,Year,Age Group,Sex,Region,UNIT,VALUE
0,Estimated Population (Persons in April),2011,0 - 4 years,Both sexes,State,Thousand,356.0
1,Estimated Population (Persons in April),2011,0 - 4 years,Both sexes,Border,Thousand,30.7
2,Estimated Population (Persons in April),2011,0 - 4 years,Both sexes,West,Thousand,32.6
3,Estimated Population (Persons in April),2011,0 - 4 years,Both sexes,Mid-West,Thousand,35.0
4,Estimated Population (Persons in April),2011,0 - 4 years,Both sexes,South-East,Thousand,32.0

In [500]:
df.index

RangeIndex(start=0, stop=6669, step=1)

In [501]:
df.isna().sum()

STATISTIC Label    0
Year               0
Age Group          0
Sex                0
Region             0
UNIT               0
VALUE              0
dtype: int64

In [502]:
df.dtypes

STATISTIC Label     object
Year                 int64
Age Group           object
Sex                 object
Region              object
UNIT                object
VALUE              float64
dtype: object

In [503]:
df.describe()

              Year        VALUE
count  6669.000000  6669.000000
mean   2017.000000    75.670460
std       3.741938   281.512172
min    2011.000000     1.200000
25%    2014.000000    12.500000
50%    2017.000000    20.700000
75%    2020.000000    42.200000
max    2023.000000  5281.600000

In [504]:
df.columns

Index(['STATISTIC Label', 'Year', 'Age Group', 'Sex', 'Region', 'UNIT',
       'VALUE'],
      dtype='object')

In [505]:

# changing the columns name to make it easy to understand.
# inplace = True set the valuses parmently so that we can use the new columns names
df.rename(columns={'STATISTIC Label': 'statistic_label', 'Year': 'year', 'Age Group':'age_group', 'Sex':'sex', 'Region':'region', 'UNIT':'unit','VALUE':'value'},inplace=True)

In [506]:
df.head()

,statistic_label,year,age_group,sex,region,unit,value
0,Estimated Population (Persons in April),2011,0 - 4 years,Both sexes,State,Thousand,356.0
1,Estimated Population (Persons in April),2011,0 - 4 years,Both sexes,Border,Thousand,30.7
2,Estimated Population (Persons in April),2011,0 - 4 years,Both sexes,West,Thousand,32.6
3,Estimated Population (Persons in April),2011,0 - 4 years,Both sexes,Mid-West,Thousand,35.0
4,Estimated Population (Persons in April),2011,0 - 4 years,Both sexes,South-East,Thousand,32.0

In [507]:
#now drop tha table one that is "statistic_label" because there is no any usefull data only text is reperting throught the table  so eliminate it
df.drop({'statistic_label', 'unit'}, axis=1, inplace=True)

In [508]:
## and the valuse are in thousand to we multiply the values column in thousand
df['value'] = df['value']*1000

In [509]:
df.head(20)
#2011	0 - 4 years	Male	State

    year    age_group         sex      region     value
0   2011  0 - 4 years  Both sexes       State  356000.0
1   2011  0 - 4 years  Both sexes      Border   30700.0
2   2011  0 - 4 years  Both sexes        West   32600.0
3   2011  0 - 4 years  Both sexes    Mid-West   35000.0
4   2011  0 - 4 years  Both sexes  South-East   32000.0
5   2011  0 - 4 years  Both sexes  South-West   50100.0
6   2011  0 - 4 years  Both sexes      Dublin   93300.0
7   2011  0 - 4 years  Both sexes    Mid-East   58500.0
8   2011  0 - 4 years  Both sexes     Midland   23900.0
9   2011  0 - 4 years        Male       State  182000.0
10  2011  0 - 4 years        Male      Border   15800.0
11  2011  0 - 4 years        Male        West   16600.0
12  2011  0 - 4 years        Male    Mid-West   18000.0
13  2011  0 - 4 years        Male  South-East   16400.0
14  2011  0 - 4 years        Male  South-West   25500.0
15  2011  0 - 4 years        Male      Dublin   47600.0
16  2011  0 - 4 years        Male    Mid-East   29700.0
17  2011  0 - 4 years        Male     Midland   12300.0
18  2011  0 - 4 years      Female       State  174100.0
19  2011  0 - 4 years      Female      Border   15000.0

In [534]:
# filt1 = (df['age_group'] == '0 - 4 years') & (df['sex'] == 'Both sexes') & (df['region'] == 'State')
filt_border = df.loc[(df['sex'] == 'Both sexes') & (df['region'] == 'Border') & (df['age_group'] == 'All ages')].reset_index(level=None)
filt_west = df.loc[(df['sex'] == 'Both sexes') & (df['region'] == 'West') & (df['age_group'] == 'All ages')].reset_index(level =None)
filt_mwest = df.loc[(df['sex'] == 'Both sexes') & (df['region'] == 'Mid-West') & (df['age_group'] == 'All ages')].reset_index(level =None)
filt_seast = df.loc[(df['sex'] == 'Both sexes') & (df['region'] == 'Border') & (df['age_group'] == 'All ages')].reset_index(level=None)
filt_swest = df.loc[(df['sex'] == 'Both sexes') & (df['region'] == 'West') & (df['age_group'] == 'All ages')].reset_index(level =None)
filt_dublin = df.loc[(df['sex'] == 'Both sexes') & (df['region'] == 'Border') & (df['age_group'] == 'All ages')].reset_index(level=None)
filt_meast = df.loc[(df['sex'] == 'Both sexes') & (df['region'] == 'Border') & (df['age_group'] == 'All ages')].reset_index(level=None)
filt_mland = df.loc[(df['sex'] == 'Both sexes') & (df['region'] == 'Border') & (df['age_group'] == 'All ages')].reset_index(level=None)
border_value = filt_border['value']
west_value = filt_west['value']
mwest_value = filt_mwest['value']
seast_value = filt_seast['value']
swest_value = filt_swest['value']
dublin_value = filt_dublin['value']
meast_value = filt_meast['value']
mland_value = filt_mland['value']
mland_value

0     391900.0
1     392100.0
2     393100.0
3     392000.0
4     391900.0
5     393300.0
6     400300.0
7     405700.0
8     409900.0
9     412000.0
10    417100.0
11    422200.0
12    432100.0
Name: value, dtype: float64

In [535]:
total_pop = np.array(['west'= west_value,mwest_value,seast_value,swest_value,dublin_value,meast_value,mland_value])

total_pop

array([[440800., 439400., 441700., 441100., 442200., 447500., 453100.,
        458700., 464800., 472200., 475400., 486700., 500800.],
       [466800., 470600., 470700., 471800., 473400., 472500., 480200.,
        489000., 493400., 497900., 499600., 508700., 519600.],
       [391900., 392100., 393100., 392000., 391900., 393300., 400300.,
        405700., 409900., 412000., 417100., 422200., 432100.],
       [440800., 439400., 441700., 441100., 442200., 447500., 453100.,
        458700., 464800., 472200., 475400., 486700., 500800.],
       [391900., 392100., 393100., 392000., 391900., 393300., 400300.,
        405700., 409900., 412000., 417100., 422200., 432100.],
       [391900., 392100., 393100., 392000., 391900., 393300., 400300.,
        405700., 409900., 412000., 417100., 422200., 432100.],
       [391900., 392100., 393100., 392000., 391900., 393300., 400300.,
        405700., 409900., 412000., 417100., 422200., 432100.]])

In [ ]:
sns.lineplot(data=flights_wide["May"])
sns.lineplot(filt_west['year'], west_value, label='west')
plt.plot(filt_west['year'], border_value, label='state')
plt.plot(filt_west['year'], mwest_value, label='m-west')
plt.plot(filt_west['year'], seast_value, label='s-east')
plt.plot(filt_west['year'], swest_value, label='s-west')
plt.plot(filt_west['year'], dublin_value, label='dublin')
plt.plot(filt_west['year'], meast_value, label='m-east')
plt.plot(filt_west['year'], mland_value, label='m-land')
plt.legend()

In [ ]:
fig, BarGraph = plt.subplots(figsize=(12, 5))
bar_colors = ['#CD5555','#CD5777','#CD3455','#CD8977', '#FF00FF', '#EE30A7', '#B452CD', '#F5FFFA','#EEB4B4', '#436EEE', '#FA8072', '#3A5FCD', '#FF8072']
BarGraph.plot(filt_west['year'], west_value, label='west')
BarGraph.plot(filt_west['year'], border_value, label='state')
BarGraph.plot(filt_west['year'], mwest_value, label='m-west')
BarGraph.plot(filt_west['year'], seast_value, label='s-east')
BarGraph.plot(filt_west['year'], swest_value, label='s-west')
BarGraph.plot(filt_west['year'], dublin_value, label='dublin')
BarGraph.plot(filt_west['year'], meast_value, label='m-east')
BarGraph.plot(filt_west['year'], mland_value, label='m-land')
# BarGraph.plot(filt_state['year'], filt_state['value'], linewidth= 1.5)
plt.xlabel('Years')
plt.ylabel('Values in thousand')
plt.title("Population of west in eact year form 2011 - 2023 of all age group")
plt.legend()
plt.show()

In [ ]:
 # we can see that there is slightly decrease in population for 2011 to 2023 which indicate that the birth rate has decresed by
#now calculate the change

In [ ]:
every_year_decreased = -17.47191 / 12
every_year_decreased
# about 1.4559925 % the birth rate is decreasing every year

In [ ]:
state_filt = (df['sex'] == 'Both sexes') & (df['region'] == 'State') & (df['age_group'] == 'All ages')
state_pop = df.loc[state_filt]

In [ ]:
state_pop.dtypes

In [ ]:
state_pop['year'].astype('int32')

In [ ]:
#total population in each year form 2011 to 2023
year = pd.to_datetime(state_pop['year'], format= '%Y')
values = state_pop['value']
fig, BarGraph = plt.subplots(figsize=(12, 5))
bar_colors = ['#CD5555','#CD5777','#CD3455','#CD8977', '#FF00FF', '#EE30A7', '#B452CD', '#F5FFFA','#EEB4B4', '#436EEE', '#FA8072', '#3A5FCD', '#FF8072']
BarGraph.plot(year, values, )
# BarGraph.bar(pop_2011['year'], pop_2011['value']/1000, color = bar_colors)
plt.xlabel('Years')
plt.ylabel('Values in thousand')
plt.title("Population in States form 2011 - 2023 of All ages group")
# plt.show()

In [ ]:
plt.plot(state_pop['year'], state_pop['value'], marker='1', label='All age', linewidth = 1)
plt.xlabel('values in thousand')
plt.ylabel('year')
plt.title("Population in States form 2011 - 2023 of All ages group")
plt.show()